apiVersion: v1
kind: PersistentVolume
metadata:
  name: test3
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/nginx"
